# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/PoC/Hilbert242C/Hilbert_242.srcs/sources_1/bd/Hilbert_242/ip/Hilbert_242_clk_wiz_0_0/Hilbert_242_clk_wiz_0_0.xci
# IP: The module: 'Hilbert_242_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/PoC/Hilbert242C/Hilbert_242.gen/sources_1/bd/Hilbert_242/ip/Hilbert_242_clk_wiz_0_0/Hilbert_242_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Hilbert_242_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/PoC/Hilbert242C/Hilbert_242.gen/sources_1/bd/Hilbert_242/ip/Hilbert_242_clk_wiz_0_0/Hilbert_242_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Hilbert_242_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/PoC/Hilbert242C/Hilbert_242.gen/sources_1/bd/Hilbert_242/ip/Hilbert_242_clk_wiz_0_0/Hilbert_242_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Hilbert_242_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/PoC/Hilbert242C/Hilbert_242.srcs/sources_1/bd/Hilbert_242/ip/Hilbert_242_clk_wiz_0_0/Hilbert_242_clk_wiz_0_0.xci
# IP: The module: 'Hilbert_242_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/PoC/Hilbert242C/Hilbert_242.gen/sources_1/bd/Hilbert_242/ip/Hilbert_242_clk_wiz_0_0/Hilbert_242_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Hilbert_242_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/PoC/Hilbert242C/Hilbert_242.gen/sources_1/bd/Hilbert_242/ip/Hilbert_242_clk_wiz_0_0/Hilbert_242_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Hilbert_242_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/PoC/Hilbert242C/Hilbert_242.gen/sources_1/bd/Hilbert_242/ip/Hilbert_242_clk_wiz_0_0/Hilbert_242_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Hilbert_242_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
