# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Zybo-Z7-Hilbert.xdc

# Block Designs: bd/Hilbert_242/Hilbert_242.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hilbert_242 || ORIG_REF_NAME==Hilbert_242} -quiet] -quiet

# IP: bd/Hilbert_242/ip/Hilbert_242_processing_system7_0_0/Hilbert_242_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hilbert_242_processing_system7_0_0 || ORIG_REF_NAME==Hilbert_242_processing_system7_0_0} -quiet] -quiet

# IP: bd/Hilbert_242/ip/Hilbert_242_main_0_0/Hilbert_242_main_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hilbert_242_main_0_0 || ORIG_REF_NAME==Hilbert_242_main_0_0} -quiet] -quiet

# IP: ip/fir_compiler_1/fir_compiler_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_compiler_1 || ORIG_REF_NAME==fir_compiler_1} -quiet] -quiet

# IP: ip/fir_compiler_0/fir_compiler_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_compiler_0 || ORIG_REF_NAME==fir_compiler_0} -quiet] -quiet

# IP: ip/xadc_wiz_0/xadc_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xadc_wiz_0 || ORIG_REF_NAME==xadc_wiz_0} -quiet] -quiet

# IP: bd/Hilbert_242/ip/Hilbert_242_axi_gpio_0_0/Hilbert_242_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hilbert_242_axi_gpio_0_0 || ORIG_REF_NAME==Hilbert_242_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Hilbert_242/ip/Hilbert_242_axi_smc_0/Hilbert_242_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hilbert_242_axi_smc_0 || ORIG_REF_NAME==Hilbert_242_axi_smc_0} -quiet] -quiet

# IP: bd/Hilbert_242/ip/Hilbert_242_rst_ps7_0_100M_0/Hilbert_242_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hilbert_242_rst_ps7_0_100M_0 || ORIG_REF_NAME==Hilbert_242_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Hilbert_242/ip/Hilbert_242_ila_0_0/Hilbert_242_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hilbert_242_ila_0_0 || ORIG_REF_NAME==Hilbert_242_ila_0_0} -quiet] -quiet

# IP: bd/Hilbert_242/ip/Hilbert_242_clk_wiz_0_0/Hilbert_242_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hilbert_242_clk_wiz_0_0 || ORIG_REF_NAME==Hilbert_242_clk_wiz_0_0} -quiet] -quiet

# XDC: /mnt/de61cc03-ca5c-4d86-98c7-744c0a68fa55/CAS_Mikroelektronik_Digital/Projekte/Hilbert_242/Hilbert_242.gen/sources_1/bd/Hilbert_242/Hilbert_242_ooc.xdc
